spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none

    properties.hibernate.search.backend.directory.type: local-heap #https://discourse.hibernate.org/t/hibernate-search-6-and-spring-boot-and-testing/5340/2 and https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#search-configuration-directory